import type { Location } from "@/data/locations";

/** Matches slugs like gtadb-l1-vice-beach-1409-2803 */
export const GTADB_SLUG_PATTERN = /gtadb-l\d+/;

type LocationIndexingFields = Pick<
  Location,
  "slug" | "name" | "description"
> & {
  source?: string;
};

export function isGtadbAutoGeneratedSlug(slug: string): boolean {
  return slug.includes("gtadb") || GTADB_SLUG_PATTERN.test(slug);
}

/** Thin editorial stubs — keep on site for map pins, exclude from SEO/AdSense crawl surface */
const THIN_STUB_SLUGS = new Set([
  "hidden-package-01",
  "grassroots-weapons",
  "everglades-lookout",
]);

export function isThinStubLocation(
  location: LocationIndexingFields,
): boolean {
  return THIN_STUB_SLUGS.has(location.slug);
}

export function isGtadbAutoGeneratedLocation(
  location: LocationIndexingFields,
): boolean {
  if (location.source === "gtadb") return true;
  if (isGtadbAutoGeneratedSlug(location.slug)) return true;
  if (location.description.includes("community-mapped location")) return true;
  if (location.name.includes("community-mapped location")) return true;
  return false;
}

/** Sample collectible pins — map only, not individual SEO pages */
const COLLECTIBLE_SEED_PREFIXES = [
  "hidden-package-",
  "stunt-jump-",
  "street-art-",
  "wildlife-",
] as const;

export function isCollectibleSeedLocation(
  location: LocationIndexingFields & { category?: string },
): boolean {
  if (location.category === "collectible") return true;
  return COLLECTIBLE_SEED_PREFIXES.some((p) => location.slug.startsWith(p));
}

export function shouldNoindexLocation(
  location: LocationIndexingFields & { category?: string },
): boolean {
  return (
    isGtadbAutoGeneratedLocation(location) ||
    isThinStubLocation(location) ||
    isCollectibleSeedLocation(location)
  );
}

export function getIndexableLocations(locations: Location[]): Location[] {
  return locations.filter((loc) => !shouldNoindexLocation(loc));
}
