import type { Location } from "@/data/locations";

/** Matches slugs like gtadb-l1-vice-beach-1409-2803 */
export const GTADB_SLUG_PATTERN = /gtadb-l\d+/;

type LocationIndexingFields = Pick<
  Location,
  "slug" | "name" | "description"
> & {
  source?: string;
};

export function isGtadbAutoGeneratedSlug(slug: string): boolean {
  return slug.includes("gtadb") || GTADB_SLUG_PATTERN.test(slug);
}

export function isGtadbAutoGeneratedLocation(
  location: LocationIndexingFields,
): boolean {
  if (location.source === "gtadb") return true;
  if (isGtadbAutoGeneratedSlug(location.slug)) return true;
  if (location.description.includes("community-mapped location")) return true;
  if (location.name.includes("community-mapped location")) return true;
  return false;
}

export function getIndexableLocations(locations: Location[]): Location[] {
  return locations.filter((loc) => !isGtadbAutoGeneratedLocation(loc));
}
