# Map-6 — Next.js standalone for Cloud Run
FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS builder
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_SITE_URL=https://map-6.com
ARG NEXT_PUBLIC_GTADB_ENABLED=true
ARG NEXT_PUBLIC_GTADB_NATIVE=false
ARG NEXT_PUBLIC_GTADB_MAP_IMAGE=/tiles/leonida-stitched.jpg
ARG NEXT_PUBLIC_MAP_MIN_X=-16384
ARG NEXT_PUBLIC_MAP_MAX_X=3584
ARG NEXT_PUBLIC_MAP_MIN_Y=-8064
ARG NEXT_PUBLIC_MAP_MAX_Y=12032
ARG NEXT_PUBLIC_MAP_CENTER_X=-6400
ARG NEXT_PUBLIC_MAP_CENTER_Y=1984
ARG NEXT_PUBLIC_MAP_MAX_ZOOM=6
ARG NEXT_PUBLIC_ADSENSE_CLIENT=ca-pub-9449600740636411
ARG NEXT_PUBLIC_ADSENSE_SLOT_BANNER=9174557090
ARG NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE=2336997643
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID=G-014MS4346K
ARG NEXT_PUBLIC_AMAZON_AFFILIATE_TAG=map6-21
ARG NEXT_PUBLIC_AMAZON_STORE=https://www.amazon.fr
ARG NEXT_PUBLIC_AMAZON_ASIN_GTA6_PS5=
ARG NEXT_PUBLIC_AMAZON_ASIN_GTA6_XBOX=
ARG NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_PS5=
ARG NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_XBOX=
ARG NEXT_PUBLIC_AMAZON_ASIN_PS5=B0FX2VBNMF
ARG NEXT_PUBLIC_AMAZON_ASIN_XBOX_SERIES_X=B08H93ZRLL
ARG NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE=B094WLFGD3
ARG NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_WHITE=B08H99BPJN
ARG NEXT_PUBLIC_AMAZON_ASIN_XBOX_PAD=B08SRMPBRF
ARG NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_EDGE=B0DSPX3R62
ARG NEXT_PUBLIC_AMAZON_ASIN_PULSE_3D=B0DSPWT99L
ARG NEXT_PUBLIC_AMAZON_ASIN_ARCTIS_NOVA=B0D1KCF7L2
ARG NEXT_PUBLIC_AMAZON_ASIN_SSD_1TB=B0B7CKZGN6
ARG NEXT_PUBLIC_AMAZON_ASIN_CAPTURE_CARD=B09V1KJ3J4
ARG NEXT_PUBLIC_AMAZON_ASIN_CHARGE_DOCK=B08S3FMVV7

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GTADB_ENABLED=$NEXT_PUBLIC_GTADB_ENABLED
ENV NEXT_PUBLIC_GTADB_NATIVE=$NEXT_PUBLIC_GTADB_NATIVE
ENV NEXT_PUBLIC_GTADB_MAP_IMAGE=$NEXT_PUBLIC_GTADB_MAP_IMAGE
ENV NEXT_PUBLIC_MAP_MIN_X=$NEXT_PUBLIC_MAP_MIN_X
ENV NEXT_PUBLIC_MAP_MAX_X=$NEXT_PUBLIC_MAP_MAX_X
ENV NEXT_PUBLIC_MAP_MIN_Y=$NEXT_PUBLIC_MAP_MIN_Y
ENV NEXT_PUBLIC_MAP_MAX_Y=$NEXT_PUBLIC_MAP_MAX_Y
ENV NEXT_PUBLIC_MAP_CENTER_X=$NEXT_PUBLIC_MAP_CENTER_X
ENV NEXT_PUBLIC_MAP_CENTER_Y=$NEXT_PUBLIC_MAP_CENTER_Y
ENV NEXT_PUBLIC_MAP_MAX_ZOOM=$NEXT_PUBLIC_MAP_MAX_ZOOM
ENV NEXT_PUBLIC_ADSENSE_CLIENT=$NEXT_PUBLIC_ADSENSE_CLIENT
ENV NEXT_PUBLIC_ADSENSE_SLOT_BANNER=$NEXT_PUBLIC_ADSENSE_SLOT_BANNER
ENV NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE=$NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_AMAZON_AFFILIATE_TAG=$NEXT_PUBLIC_AMAZON_AFFILIATE_TAG
ENV NEXT_PUBLIC_AMAZON_STORE=$NEXT_PUBLIC_AMAZON_STORE
ENV NEXT_PUBLIC_AMAZON_ASIN_GTA6_PS5=$NEXT_PUBLIC_AMAZON_ASIN_GTA6_PS5
ENV NEXT_PUBLIC_AMAZON_ASIN_GTA6_XBOX=$NEXT_PUBLIC_AMAZON_ASIN_GTA6_XBOX
ENV NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_PS5=$NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_PS5
ENV NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_XBOX=$NEXT_PUBLIC_AMAZON_ASIN_GTA6_COLLECTORS_XBOX
ENV NEXT_PUBLIC_AMAZON_ASIN_PS5=$NEXT_PUBLIC_AMAZON_ASIN_PS5
ENV NEXT_PUBLIC_AMAZON_ASIN_XBOX_SERIES_X=$NEXT_PUBLIC_AMAZON_ASIN_XBOX_SERIES_X
ENV NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE=$NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE
ENV NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_WHITE=$NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_WHITE
ENV NEXT_PUBLIC_AMAZON_ASIN_XBOX_PAD=$NEXT_PUBLIC_AMAZON_ASIN_XBOX_PAD
ENV NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_EDGE=$NEXT_PUBLIC_AMAZON_ASIN_DUALSENSE_EDGE
ENV NEXT_PUBLIC_AMAZON_ASIN_PULSE_3D=$NEXT_PUBLIC_AMAZON_ASIN_PULSE_3D
ENV NEXT_PUBLIC_AMAZON_ASIN_ARCTIS_NOVA=$NEXT_PUBLIC_AMAZON_ASIN_ARCTIS_NOVA
ENV NEXT_PUBLIC_AMAZON_ASIN_SSD_1TB=$NEXT_PUBLIC_AMAZON_ASIN_SSD_1TB
ENV NEXT_PUBLIC_AMAZON_ASIN_CAPTURE_CARD=$NEXT_PUBLIC_AMAZON_ASIN_CAPTURE_CARD
ENV NEXT_PUBLIC_AMAZON_ASIN_CHARGE_DOCK=$NEXT_PUBLIC_AMAZON_ASIN_CHARGE_DOCK

RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Baked editorial content (file-store bootstrap when Firestore empty)
COPY --from=builder --chown=nextjs:nodejs /app/data ./data

USER nextjs
EXPOSE 8080

CMD ["node", "server.js"]
