# Map-6 — Next.js standalone for Cloud Run
FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS builder
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_SITE_URL=https://map-6.com
ARG NEXT_PUBLIC_GTADB_ENABLED=true
ARG NEXT_PUBLIC_GTADB_NATIVE=false
ARG NEXT_PUBLIC_GTADB_MAP_IMAGE=/tiles/leonida-stitched.jpg
ARG NEXT_PUBLIC_MAP_MIN_X=-16384
ARG NEXT_PUBLIC_MAP_MAX_X=3584
ARG NEXT_PUBLIC_MAP_MIN_Y=-8064
ARG NEXT_PUBLIC_MAP_MAX_Y=12032
ARG NEXT_PUBLIC_MAP_CENTER_X=-6400
ARG NEXT_PUBLIC_MAP_CENTER_Y=1984
ARG NEXT_PUBLIC_MAP_MAX_ZOOM=6
ARG NEXT_PUBLIC_ADSENSE_CLIENT=ca-pub-9449600740636411
ARG NEXT_PUBLIC_ADSENSE_SLOT_BANNER=9174557090
ARG NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE=2336997643

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GTADB_ENABLED=$NEXT_PUBLIC_GTADB_ENABLED
ENV NEXT_PUBLIC_GTADB_NATIVE=$NEXT_PUBLIC_GTADB_NATIVE
ENV NEXT_PUBLIC_GTADB_MAP_IMAGE=$NEXT_PUBLIC_GTADB_MAP_IMAGE
ENV NEXT_PUBLIC_MAP_MIN_X=$NEXT_PUBLIC_MAP_MIN_X
ENV NEXT_PUBLIC_MAP_MAX_X=$NEXT_PUBLIC_MAP_MAX_X
ENV NEXT_PUBLIC_MAP_MIN_Y=$NEXT_PUBLIC_MAP_MIN_Y
ENV NEXT_PUBLIC_MAP_MAX_Y=$NEXT_PUBLIC_MAP_MAX_Y
ENV NEXT_PUBLIC_MAP_CENTER_X=$NEXT_PUBLIC_MAP_CENTER_X
ENV NEXT_PUBLIC_MAP_CENTER_Y=$NEXT_PUBLIC_MAP_CENTER_Y
ENV NEXT_PUBLIC_MAP_MAX_ZOOM=$NEXT_PUBLIC_MAP_MAX_ZOOM
ENV NEXT_PUBLIC_ADSENSE_CLIENT=$NEXT_PUBLIC_ADSENSE_CLIENT
ENV NEXT_PUBLIC_ADSENSE_SLOT_BANNER=$NEXT_PUBLIC_ADSENSE_SLOT_BANNER
ENV NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE=$NEXT_PUBLIC_ADSENSE_SLOT_IN_ARTICLE

RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 8080

CMD ["node", "server.js"]
