import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Link } from "@/i18n/navigation";
import { LocationRichContent } from "@/components/locations/LocationRichContent";
import { LocationMap } from "@/components/map/LocationMap";
import {
  getAllLocations,
  getLocationBySlug,
  type Location,
} from "@/data/all-locations";
import { getRegionalLocationSeo } from "@/data/location-seo-content";
import { isGtadbAutoGeneratedLocation } from "@/lib/location-indexing";
import {
  buildMetadata,
  jsonLdPlace,
  jsonLdRegionalLocation,
} from "@/lib/seo";

type Props = {
  params: Promise<{ locale: string; slug: string }>;
};

export function generateStaticParams() {
  return getAllLocations().map((loc) => ({ slug: loc.slug }));
}

export async function generateMetadata({ params }: Props) {
  const { locale, slug } = await params;
  const location = getLocationBySlug(slug);
  if (!location) return {};

  const isGtadbAutoGenerated = isGtadbAutoGeneratedLocation(location);
  const robots = isGtadbAutoGenerated
    ? { index: false, follow: false }
    : { index: true, follow: true };

  const regionalSeo = getRegionalLocationSeo(slug, locale);

  if (regionalSeo) {
    const titleByLocale: Record<string, string> = {
      fr: `${location.name} GTA 6 — Carte, collectibles & guide | Map-6`,
      es: `${location.name} GTA 6 — Mapa, coleccionables y guía | Map-6`,
    };

    return buildMetadata({
      locale,
      title:
        titleByLocale[locale] ??
        `${location.name} GTA 6 — Map, Collectibles & Guide | Map-6`,
      description: regionalSeo.metaDescription,
      path: `/locations/${location.slug}`,
      openGraphType: "article",
      robots,
    });
  }

  return buildMetadata({
    locale,
    title: `${location.name} — GTA 6 Map | Map-6`,
    description: location.description,
    path: `/locations/${location.slug}`,
    robots,
  });
}

const CATEGORY_LABELS: Record<Location["category"], string> = {
  landmark: "Landmark",
  collectible: "Collectible",
  shop: "Shop",
  mission: "Mission",
  secret: "Secret",
};

export default async function LocationPage({ params }: Props) {
  const { locale, slug } = await params;
  setRequestLocale(locale);

  const t = await getTranslations("locations");
  const location = getLocationBySlug(slug);
  if (!location) notFound();

  const isGtadbAutoGenerated = isGtadbAutoGeneratedLocation(location);
  const regionalSeo = getRegionalLocationSeo(slug, locale);

  const jsonLd = regionalSeo
    ? jsonLdRegionalLocation(
        location.name,
        location.slug,
        regionalSeo.schemaDescription,
        regionalSeo.faq,
      )
    : jsonLdPlace(location);

  return (
    <>
      {isGtadbAutoGenerated && (
        <meta name="robots" content="noindex,nofollow" />
      )}

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <main className="flex-1">
        <div className="mx-auto max-w-5xl px-4 py-8">
          <Link
            href="/locations"
            className="mb-4 inline-block text-sm text-white/50 hover:text-white"
          >
            {t("backToAll")}
          </Link>

          <div className="mb-6">
            <span className="mb-2 inline-block rounded-full bg-pink-500/20 px-3 py-1 text-xs font-medium text-pink-300">
              {CATEGORY_LABELS[location.category]}
            </span>
            <h1 className="text-3xl font-bold">{location.name}</h1>
            <p className="mt-1 text-sm text-white/50">{location.region}</p>
          </div>

          <p className="mb-6 max-w-2xl text-white/70">{location.description}</p>

          <p className="mb-4 font-mono text-sm text-white/40">
            {t("coordinates", { x: location.x, y: location.y })}
          </p>

          <Link
            href={`/map?x=${location.x}&y=${location.y}`}
            className="mb-8 inline-block rounded-full bg-pink-500 px-6 py-2 text-sm font-semibold text-white hover:bg-pink-400"
          >
            {t("viewOnMap")}
          </Link>

          {regionalSeo && (
            <LocationRichContent name={location.name} seo={regionalSeo} />
          )}
        </div>

        <div className="h-80 border-t border-white/10">
          <LocationMap x={location.x} y={location.y} />
        </div>
      </main>
    </>
  );
}
